CREATE DATABASE GameTube;

USE GAMETUBE;

CREATE TABLE MEMENTO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50),
    USERNAME VARCHAR(100),
    EMAIL VARCHAR(200),
    SENHA VARCHAR(50),
    USER_ADMIN BOOLEAN
);

CREATE TABLE USUARIO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMENTO_ID INT,
    NOME VARCHAR(50),
    USERNAME VARCHAR(100),
    EMAIL VARCHAR(200),
    SENHA VARCHAR(50),
    FOREIGN KEY(MEMENTO_ID) REFERENCES MEMENTO(ID)
);

CREATE TABLE ADM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMENTO_ID INT,
    NOME VARCHAR(50),
    USERNAME VARCHAR(100),
    EMAIL VARCHAR(200),
    SENHA VARCHAR(50),
    ADMINISTRADOR BOOLEAN,
    FOREIGN KEY(MEMENTO_ID) REFERENCES MEMENTO(ID)
);

CREATE TABLE USUARIO_FOTO(
	ID INT AUTO_INCREMENT,
    ID_USUARIO INT,
    PICTURE BLOB,
    PRIMARY KEY(ID, ID_USUARIO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE ADM_FOTO(
	ID INT AUTO_INCREMENT,
    ID_ADM INT,
    PICTURE BLOB,
    PRIMARY KEY(ID, ID_ADM),
    FOREIGN KEY (ID_ADM) REFERENCES ADM(ID)
);

CREATE TABLE GAME(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100),
    DESCRICAO VARCHAR(200),
    PRECO DOUBLE
);

CREATE TABLE GAME_FOTO(
	ID INT AUTO_INCREMENT,
    ID_GAME INT,
    PICTURE BLOB,
    PRIMARY KEY(ID,ID_GAME),
	FOREIGN KEY(ID_GAME) REFERENCES GAME(ID)
);

CREATE TABLE BIBLIOTECA(
	ID_GAME INT,
    ID_USUARIO INT,
    PRIMARY KEY(ID_GAME, ID_USUARIO),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY(ID_GAME)    REFERENCES GAME(ID)
);